version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: MathELearning
      POSTGRES_USER: elearning_user
      POSTGRES_PASSWORD: 123
    # ports:
      # - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapi
    container_name: myapi_container
    depends_on:
      - postgres
    ports:
      - "80:8080"
    env_file:
      - .env
    restart: always

  # AI chính (Gemini / xử lý core)
  ai_core:
    build: ./AI
    container_name: ai_core
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env

  # Chatbot API
  ai_chatbot:
    build:
      context: ./AI
      dockerfile: Dockerfile.chatbot
    container_name: ai_chatbot
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - .env

volumes:
  pgdata:
