version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: MathELearning
      POSTGRES_USER: elearning_user
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    image: myapi
    container_name: myapi_container
    depends_on:
      - postgres
    ports:
      - "80:8080"
    environment:
      ConnectionStrings__MyCnn: "Host=postgres;Port=5432;Database=MathELearning;Username=elearning_user;Password=123"
      JwtSettings__SecretKey: "FnKmfgu94hp4XxOMCWXOKm4jtFc8K79v"
      JwtSettings__Issuer: "ELearningAPI"
      JwtSettings__Audience: "ELearningClient"
    restart: always

volumes:
  pgdata:
